### ISSUE TITLE
Use something other than h,j,k,l for movement

### ISSUE THREAD

**Issue by nobleach** [matze/vim-move#13]
I've looking into using something other than the default movement keys. I didn't know if this was already on your radar or not. I'd love to use my arrow keys as I'd rather use CTRL+J/CTRL+K for more used purposes.

**Comment by vitalk** [comment]
Disable default keys and bind your own via defined `<Plug>` mappings:

```viml
let g:move_map_keys = 0
vmap <C-j> <Plug>MoveBlockDown
```

See `:h move-mappings` for list of available mappings.

**Comment by nobleach** [comment]
Beautiful, thanks.
