### ISSUE TITLE
Can't move in normal mode

### ISSUE THREAD

**Issue by tthanh** [matze/vim-move#14]
When setting this plugin, I can move line in normal mode in vimrc file, but when open another file like sh or ruby file, I only can move in visual mode, normal mode don't work.
My vimrc config:
```
let g:move_map_keys = 0
nmap <C-k> <Plug>MoveLineUp
nmap <C-j> <Plug>MoveLineDown
vmap <C-k> <Plug>MoveBlockUp
vmap <C-j> <Plug>MoveBlockDown
```
Ubuntu 15.04, vim 7.4 patch 699 custom build

**Comment by matze** [comment]
It works for me. Have you checked with `:nmap` that no other plugins map these keys?

**Comment by tthanh** [comment]
@matze Thank you so much, I just found <C-j> and <C-k> use in vim-tmux-navigator plugin.
