### ISSUE TITLE
Does not work under OSX

### ISSUE THREAD

**Issue by hyiltiz** [matze/vim-move#17]
After installing though vim-plug and restarting vim, pressing Alt+J etc. does nothing.

**Comment by matze** [comment]
I suppose it's due to your terminal emulator's handling of the meta key. Solutions have been discussed in #8 and #15 before. If you think it's caused by something else, don't hesitate to re-open this issue.

**Comment by hyiltiz** [comment]
Yes, that did solve. Thanks!
