### ISSUE TITLE
Crashing and CPU hog

### ISSUE THREAD

**Issue by IhsanE** [matze/vim-move#19]
This plugin repeatedly crashes if you hold down `j` or `k` to move a line up or down continuously. 

The crash of vim results in 59% of CPU time being taken up; which consumes 100% of an entire core. The only way to resolve the crash is by `SIGKILLING` the process.

**Comment by matze** [comment]
I cannot reproduce this behaviour. Are you sure it's this plugin by disabling *all* other plugins and just load this?

**Comment by matze** [comment]
Re-open if this is still a problem.
