### ISSUE TITLE
Instructions unclear.

### ISSUE THREAD

**Issue by cookiengineer** [matze/vim-move#21]
How do I use this plugin?

I was trying to remap it to using 'Alt' as a key leader to find out whether another key binding conflicts.
I think I don't get how to use this plugin.

What I was trying out is (given `let g:move_key_modifier='Alt'`):

- Be in normal mode
- Switch to visual mode using ~~v or ctrl+v~~ shift+v (v-line mode)
- Select a few lines of text
- Press alt+j or alt+k.
- Visual mode ends, nothing happens!?

Using Shift-A as a leader directly exists visual mode in my vimrc, no idea what to change to make this work, as Alt + j/k/whatever is pretty much unbound.

What is the _workflow_ of this plugin to use it? I guess I misinterpreted how to use this correctly.

**Comment by matze** [comment]
> What is the workflow of this plugin to use it?

Figuring out how your OS and terminal translates keycodes to something Vim understands. First of all, Vim does not know `Alt`, it's either `A` or `M`. However, that does not mean the terminal will generate something Vim will understand as `A` or `M`. With GNOME terminal I have to map unprintable [characters](https://github.com/matze/configs/blob/7ef8ab1e9a56e5e278a88f42f97dc9367aeddcb9/.vimrc#L155-L158) to be able to map the alt key.

**Comment by cookiengineer** [comment]
Woah, thank you very much!

That let me to [this stackoverflow question](https://stackoverflow.com/questions/6778961/alt-key-shortcuts-not-working-on-gnome-terminal-with-vim) that shows how to map Alt Keys in terminals via escape sequences.
