### ISSUE TITLE
How to restore the position in the line after moving?

### ISSUE THREAD

**Issue by c02y** [matze/vim-move#33]
Currently when you are in the middle of the line, and using vim-move to move the current line, then the point of the cursor will be placed at the beginning of the line.

This is annoying when the word of the point before moving is important, and when I have multiple such lines(not in a block) to move, then I have to keep moving back to the middle of the line(the old point) manually.

Is it possible to make the point untouched when moving line(s) or restore the point in the line after moving line(s)?

**Comment by matze** [comment]
Unfortunately, the builtin command that the plugin wraps automatically moves the cursor. I suppose it's possible to reset the cursor but I'll better wait for a PR.

**Comment by c02y** [comment]
Actually, you can save the column into a variable using `col(".")` before moving, and jump to the col using the saved variable after moving.
