### ISSUE TITLE
Moving block including indents

### ISSUE THREAD

**Issue by tom-adsfund** [matze/vim-move#40]
If I have something like below and try to move lines 2-3 together, they will not maintain the indents -- 3 will be moved to the level of 2. The level difference should be maintained.

```
1
   2
      3
4
```

When I'm working with indented notes maintaining level differences is essential.

**Comment by hugomg** [comment]
As a workaround, you can disable the automatic indentation feature.

        let g:move_auto_indent = 0

**Comment by tom-adsfund** [comment]
@matze Great, thanks!

**Comment by matze** [comment]
Don't thank me, thank @hugomg who is implementing a ton of awesome improvements.

**Comment by tom-adsfund** [comment]
@matze Sure. Thanks @hugomg !!!
