### ISSUE TITLE
Moving by multiple lines does not work anymore

### ISSUE THREAD

**Issue by hugomg** [matze/vim-move#42]
When I try moving a line multiple times at once with `5<A-k>`, it only moves it by one line. I tested old versions of the plugin and I think that the commit that broke this functionality was 0d4737ce. However, I am not 100% sure.

I use Neovim 0.4.3 but I think the issue also happens in regular Vim.

**Comment by matze** [comment]
@yukunlin can you imagine why this happens?

**Comment by homogulosus** [comment]
I am running neovim on Mac and plugging does not work either. No idea what could cause this.
