### ISSUE TITLE
Ridiculously high CPU usage when moving lines horizontally

### ISSUE THREAD

**Issue by Nova-Striker** [matze/vim-move#58]
As the title says, `vim-move` ramps up all my 8 cpus to near 100% when doing a horizontal move. So much that even neovim starts to lag.
So is there any fix to this?

![Peek 2020-11-19 23-04](https://user-images.githubusercontent.com/64089730/99702403-bc387680-2abb-11eb-95e4-b520adc0bb7a.gif)

**Comment by matze** [comment]
>  So is there any fix to this?

Try disabling other plugins. I cannot reproduce this issue.

**Comment by Nova-Striker** [comment]
Nevermind. I checked it with all other plugins disabled and I too was unable to reproduce the issue
