### ISSUE TITLE
How to use this Plugin with arrow keys?

### ISSUE THREAD

**Issue by maxreuben** [matze/vim-move#64]
How can i retool this plugin to make it use arrow keys instead of hjkl? Is it possible? I don't know Vimscript so I can't really tell.

**Comment by matze** [comment]
Disable auto-mapping and then bind `<Up>` and `<Down>` as usual, i.e.

```
let g:move_map_keys = 0

vmap <Down> <Plug>MoveBlockDown
vmap <Up> <Plug>MoveBlockUp
nmap <Down> <Plug>MoveLineDown
nmap <Up> <Plug>MoveLineUp
```

**Comment by maxreuben** [comment]
Thank you for your help.

**Comment by maxreuben** [comment]
Neither Alt nor Ctrl keys are working in any of my terminals (alacritty, gnome-terminal, tabby). Is there a way to prevent the terminal from prefixing the ESC character somehow? Or at least a workaround do that that it can be mapped in vim? I tried this:
```
 map <ESC>[1;5B <A-Down>
 map <ESC>[1;5A <A-Up>
 map! <ESC>[1;5B <A-Down>
 map! <ESC>[1;5A <A-Up>
 
 let g:move_map_keys = 0
 
 vmap <A-Down> <Plug>MoveBlockDown
 vmap <A-Up>   <Plug>MoveBlockUp
 nmap <A-Down> <Plug>MoveLineDown
 nmap <A-Up>   <Plug>MoveLineUp
```
But it didn't work.

**Comment by matze** [comment]
You can see what sequence is sent by going into insert mode, typing C-v and then typing whatever you are interested in. If I type Alt-Up in gnome-terminal I get `<M-Up>`.

**Comment by maxreuben** [comment]
Thanks, I figured it out.
