### ISSUE TITLE
How can I map J K to move block down and up?

### ISSUE THREAD

**Issue by hungpham3112** [matze/vim-move#65]
I have some key mappings but it didn't work like I expected.

   ```
let g:move_map_keys = 0
let g:move_undo_join = 0  
xnoremap J <Plug>MoveBlockDown                                                       
xnoremap K <Plug>MoveBlockUp
xnoremap H <Plug>MoveBlockLeft
xnoremap L <Plug>MoveBlockRight
```

I don't want to use default <A-j> or <C-j>. Thanks in advance

**Comment by matze** [comment]
That's not how you map uppercase keys. You have to specify the shift modifier as well, i.e. `<S-j>` for the first map.
