### ISSUE TITLE
<A-j> and <A-k> do not work

### ISSUE THREAD

**Issue by patforg** [matze/vim-move#8]
I'm unable to get the plugin to work with the default key bindings.

I've tried both left and right Alt key.

Here is the content of my .vimrc

```
set nocompatible               " be iMproved
filetype off                    " required!

set encoding=utf-8

filetype plugin on

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
Bundle 'gmarik/vundle'
Bundle 'matze/vim-move'
filetype plugin indent on     " required!
```

When I set let g:move_key_modifier = 'C' it works.  I've tried with let g:move_key_modifier = 'A' to no avail

any ideas why it's not working with the default alt key binding ?

**Comment by ejoubaud** [comment]
People reading this and interested in the escape sequence workaround might want to read about this caveat/tip: https://github.com/matze/vim-move/issues/15#issuecomment-168177827
